# Check out Codecov at: https://codecov.io/

coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    project:
      default: false
      source:
        paths:
          - src/

comment:
  layout: diff, flags, files
  behavior: default # update, if exists. Otherwise post new.
  require_changes: true # only post the comment if coverage changes
  require_base: no
  require_head: yes

flags:
  integration-MacOS:
    carryforward: true
    paths:
      - src/*.js
      - index.js
      - index.cjs
      - testing.cjs
  integration-Ubuntu:
    carryforward: true
    paths:
      - src/*.js
      - index.js
      - index.cjs
      - testing.cjs
  integration-Windows:
    carryforward: true
    paths:
      - src/*.js
      - index.js
      - index.cjs
      - testing.cjs
  unit:
    carryforward: true
    paths:
      - src/*.js

ignore:
  - script/**/*
  - test/**/*
