# Check out Codecov at: https://codecov.io/

coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    project:
      default:
        target: 95%
        flags:
          - e2e-MacOS
          - e2e-Ubuntu
          - e2e-Windows
          - integration-MacOS
          - integration-Ubuntu
          - integration-Windows
      relaxed:
        target: 10%
        flags:
          - breakage
          - compatibility
      strict:
        target: 100%
        flags:
          - unit

comment:
  layout: diff, flags, files
  behavior: default # update, if exists. Otherwise post new.
  require_changes: true # only post the comment if coverage changes
  require_base: no
  require_head: yes

flags:
  breakage:
    carryforward: true
    paths:
      - src/
  compatibility:
    carryforward: true
    paths:
      - src/
  e2e-MacOS:
    carryforward: true
    paths:
      - src/
    ignore:
      - src/modules/stateless.js
      - src/modules/testing.js
  e2e-Ubuntu:
    carryforward: true
    paths:
      - src/
    ignore:
      - src/modules/stateless.js
      - src/modules/testing.js
  e2e-Windows:
    carryforward: true
    paths:
      - src/
    ignore:
      - src/modules/stateless.js
      - src/modules/testing.js
  integration-MacOS:
    carryforward: true
    paths:
      - src/
  integration-Ubuntu:
    carryforward: true
    paths:
      - src/
  integration-Windows:
    carryforward: true
    paths:
      - src/
  unit:
    carryforward: true
    paths:
      - src/internal/

ignore:
  - script/**/*
  - test/**/*
