# Check out Labeler at: https://github.com/actions/labeler

ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/*
          - .github/dependabot.yml
          - .github/labeler.yml

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - .nvmrc
          - .tool-versions
          - package-lock.json

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/*

fuzz:
  - changed-files:
      - any-glob-to-any-file:
          - script/fuzz.js
          - test/fuzz/**

meta:
  - changed-files:
      - any-glob-to-any-file:
          - .github/ISSUE_TEMPLATE/*
          - .github/dependabot.yml
          - .github/labeler.yml
          - config/**
          - .editorconfig
          - .gitattributes
          - .gitignore
          - .licensee.json
          - .lockfile-lintrc.yml
          - .npmrc
          - .shellcheckrc

test:
  - changed-files:
      - any-glob-to-any-file:
          - config/c8/**
          - config/stryker/**
          - test/breakage/**
          - test/compat/**
          - test/e2e/**
          - test/fixtures/**
          - test/integration/**
          - test/unit/**
          - test/*

security:
  - changed-files:
      - any-glob-to-any-file:
          - .github/codeql.yml
          - .nsprc
