# Check out Labeler at: https://github.com/actions/labeler

ci/cd:
  - .github/workflows/*
  - .github/codecov.yml
  - .github/dependabot.yml
  - .github/labeler.yml

dependencies:
  - .nvmrc
  - .tool-versions
  - package-lock.json

documentation:
  - docs/*

fuzz:
  - script/fuzz.js
  - test/fuzz/**

meta:
  - .github/ISSUE_TEMPLATE/*
  - .github/dependabot.yml
  - .github/labeler.yml
  - config/**
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .licensee.json
  - .npmrc
  - .shellcheckrc

test:
  - config/c8/**
  - config/stryker/**
  - test/breakage/**
  - test/compat/**
  - test/e2e/**
  - test/fixtures/**
  - test/integration/**
  - test/unit/**
  - test/*

security:
  - .github/codeql.yml
  - .nsprc
