# Check out Labeler at: https://github.com/actions/labeler

benchmark:
  - bench/**

ci/cd:
  - .github/workflows/*
  - .github/codecov.yml
  - .github/dependabot.yml
  - .github/labeler.yml

dependencies:
  - .tool-versions
  - .nvmrc
  - package-lock.json

documentation:
  - docs/*

fuzz:
  - script/fuzz.js
  - test/fuzz/*
  - test/fuzz/**/*

meta:
  - .github/ISSUE_TEMPLATE/*
  - .github/dependabot.yml
  - .github/labeler.yml
  - .editorconfig
  - .eslintrc.yml
  - .gitignore
  - .licensee.json
  - .markdownlint.yml
  - .npmrc
  - .shellcheckrc

test:
  - test/**
  - test/**/*
  - "!test/fuzz/*"
  - "!test/fuzz/**/*"
  - stryker.*.config.js

security:
  - .github/codeql.yml
  - .nsprc
