# Check out depcheck at: https://github.com/depcheck/depcheck

ignores:
  - "@stryker-mutator/tap-runner"
  - jsfuzz
  - publint
  - rollup
ignore-path: .gitignore

parsers:
  "**/*.js": es6
  "**/*.cjs": es6
