# Check out lockfile-lint at: https://github.com/lirantal/lockfile-lint

path: package-lock.json
allowedHosts:
  - npm
  - gitlab.com
emptyHostname: false
validateHttps: true
validateIntegrity: true
validatePackageNames: false
integrityExclude:
  - "@gitlab-org/jsfuzz"
