contact_links:
  - name: Contributing Guidelines
    about: Not sure where to start? Check out the Contributing Guidelines
    url: https://github.com/ericcornelissen/shescape/blob/main/CONTRIBUTING.md
