name: Question
description: Ask a question about Shescape.
labels:
  - question
body:
  - type: markdown
    attributes:
      value: >
        Ask a question if you need help using `depreman`.

        You can also use this form if you're unsure if you found a bug or if a
        feature is missing.
  - id: version
    type: input
    attributes:
      label: Version
      description: |
        Enter the version of Shescape you are using. You can get the version by
        using `npm ls shescape`.
      placeholder: |
        v3.0.2
    validations:
      required: true
  - id: context
    type: input
    attributes:
      label: Context
      description: |
        Enter the operating system and shell you are using.
      placeholder: |
        ex. Ubuntu 26.04, Bash
    validations:
      required: false
  - id: question
    type: textarea
    attributes:
      label: Question
      description: |
        Describe what your question is and, if possible, why you have this
        question.
    validations:
      required: true
