#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Pre
if [ -z "$(IS_MERGING)" ]; then
  git stash push --quiet --include-untracked
fi

# Checks
npm run license-check
npm run format:check
npm run lint
npm run test:unit
npm run transpile

if command -v gitleaks > /dev/null; then
  gitleaks protect
fi

# Post
if [ -n "$(DID_STASH)" ]; then
  git stash pop --quiet --index
fi
