#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Pre
if [ ! "$(IS_MERGING)" ]; then
  git stash push --quiet --include-untracked --keep-index
fi

# Checks
npm run vet
npm run lint:js
npm run lint:md
npm run format
git update-index --again

if command -v gitleaks > /dev/null; then
  gitleaks protect
fi
if command -v shellcheck > /dev/null; then
  npm run lint:sh
fi

# Post
if [ "$(DID_STASH)" ]; then
  git stash pop --quiet
fi
