#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Pre
if [ ! "$(IS_MERGING)" ]; then
  git stash push --quiet --include-untracked
fi

# Checks
npm run lint
npm run eslint
npm run test
npm run transpile

# Post
if [ "$(DID_STASH)" ]; then
  git stash pop --quiet --index
fi
