#!/bin/sh
# SPDX-License-Identifier: MIT

. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Pre
if [ -z "$(IS_MERGING)" ]; then
  npm run format
  git stash push --quiet --include-untracked --keep-index
fi

# Checks
npm run license-check
npm run lint
npm run transpile
npm run vet

if command -v gitleaks > /dev/null; then
  gitleaks protect
fi

npm run format
git update-index --again

# Post
if [ -n "$(DID_STASH)" ]; then
  git stash pop --quiet
fi
