#!/bin/sh
# SPDX-License-Identifier: MIT-0

. "$(dirname "$0")/../common.sh"

# Pre
if [ -z "$(IS_MERGING)" ]; then
  npm run format
  git stash push --quiet --include-untracked --keep-index
fi

# Script
npm run check
npm run format
git update-index --again

# Post
if [ -n "$(DID_STASH)" ]; then
  git stash pop --quiet
fi
