#!/bin/sh
# SPDX-License-Identifier: MIT-0

. "$(dirname "$0")/../common.sh"

# Pre
if [ -z "$(IS_MERGING)" ]; then
  git stash push --quiet --include-untracked
fi

# Script
npm run check
npm run test:unit

# Post
if [ -n "$(DID_STASH)" ]; then
  git stash pop --quiet --index
fi
