name: Code Analysis
on:
  push:
  pull_request:
    paths:
      - "**.js"
      - ".github/workflows/analysis.yml"
      - ".github/codeql.yml"
  schedule:
    - cron: "0 7 * * 3"

permissions: read-all

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@v1.4.4
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            ghcr.io:443
            github.com:443
            pkg-containers.githubusercontent.com:443
            uploads.github.com:443
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2.1.17
        with:
          config-file: ./.github/codeql.yml
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2.1.17
  codacy:
    name: Codacy
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@v1.4.4
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.1.0
        with:
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
          output: codacy-results.sarif
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2.1.17
        with:
          sarif_file: codacy-results.sarif
