name: Audit
on:
  pull_request:
    paths:
      - .github/workflows/audit-dev.yml
      - .ndmrc
      - .nsprc
      - .nvmrc
      - package-lock.json
  push:
    branches:
      - main-v2
  workflow_dispatch: ~

permissions: read-all

jobs:
  deprecations:
    name: Deprecations
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Verify action checksums
        uses: ./.github/actions/ghasum
      - name: Install Node.js
        uses: actions/setup-node@v6.3.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Audit for deprecations
        run: npm run audit:deprecations
  vulnerabilities:
    name: Vulnerabilities
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Verify action checksums
        uses: ./.github/actions/ghasum
      - name: Install Node.js
        uses: actions/setup-node@v6.3.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Audit for vulnerabilities
        run: npm run audit:vulnerabilities
