name: Config Validation
on:
  push:
    paths:
      - ".github/codecov.yml"
      - ".github/dependabot.yml"
  pull_request:
    paths:
      - ".github/workflows/configs.yml"
      - ".github/codecov.yml"
      - ".github/dependabot.yml"

permissions: read-all

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: block
          allowed-endpoints: >
            codecov.io:443
            github.com:443
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Validate Codecov configuration
        run: |
          RESULT=$(curl -s -o /dev/null -w "%{http_code}" --data-binary @./.github/codecov.yml https://codecov.io/validate)
          if ! [[ $RESULT == "200" ]]; then
            exit 1
          fi
  dependabot:
    name: Dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Validate Dependabot configuration
        uses: marocchino/validate-dependabot@3850c9b9e1144268a169f68b5135f395ce102b43
