name: Config
on:
  pull_request:
    paths:
      - .github/workflows/configs.yml
      - .github/codecov.yml
  push:
    branches:
      - main

permissions: read-all

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            codecov.io:443
            github.com:443
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Validate Codecov configuration
        run: sh script/validate-codecov-config.sh
