name: Config Codecov
on:
  pull_request:
    paths:
      - .github/workflows/config-codecov.yml
      - .github/codecov.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/config-codecov.yml
      - .github/codecov.yml

permissions: read-all

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-22.04
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            actions-results-receiver-production.githubapp.com:443
            api.github.com:443
            codecov.io:443
            github.com:443
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Validate Codecov configuration
        uses: ericcornelissen/codecov-config-validator-action@bbb3f8ef45de6f6ce57ea8d566940bdd78b4814a # v1.0.2
