name: Config
on:
  pull_request:
    paths:
      - .github/workflows/configs.yml
      - .github/codecov.yml
  push:
    branches:
      - main

permissions: read-all

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: block
          allowed-endpoints: >
            codecov.io:443
            github.com:443
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Validate Codecov configuration
        run: sh script/validate-codecov-config.sh
