name: Config
on:
  pull_request:
    paths:
      - .github/workflows/configs.yml
      - .github/codecov.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/configs.yml
      - .github/codecov.yml

permissions: read-all

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-22.04
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codecov.io:443
            github.com:443
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Validate Codecov configuration
        uses: ericcornelissen/codecov-config-validator-action@2a3c15afd02496b4c6f5366166e4e0f610465030 # v1.0.0
