name: Test
on:
  schedule:
    - cron: "0 0 * * *"

permissions: read-all

jobs:
  fuzz:
    name: Fuzz
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@job-based-timeouts-for-fuzzing
    with:
      duration-minutes: 20
