name: Dirty Waters
on:
  pull_request: ~
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  analyze:
    name: Analysis
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write # To comment on a Pull Request
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Static Dirty Waters analysis
        uses: chains-project/dirty-waters-action@a8d5eb2c37640e3a34cf94897cb5991193466272 # v1.11.2
        with:
          allow_pr_comment: true
          comment_on_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gradual_report: false
          ignore_cache: $false
          package_manager: npm
