name: Dirty Waters
on:
  pull_request: ~
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  analyze:
    name: Analysis
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write # To comment on a Pull Request
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            files.pythonhosted.org:443
            github.com:443
            packages.microsoft.com:443
            pypi.org:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
      - name: Run Dirty-waters analysis
        uses: chains-project/dirty-waters-action@c1963faaf5c88ed7a8bb49c73d6cc2b272310658 # v1.11.44-pre-1
        with:
          allow_pr_comment: true
          comment_on_commit: false
          config: ./config/dirty-waters.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gradual_report: false
          ignore_cache: false
          package_manager: npm
          specified_smells: --check-code-signature --check-source-code --check-source-code-sha
