name: CMD
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-cmd.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/win/cmd.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-cmd.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/win/cmd.js
      - test/fuzz/**
    branches:
      - main
  schedule:
    - cron: "0 2 2 * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  fuzz:
    name: Fuzz
    uses: ./.github/workflows/reusable-fuzz.yml
    with:
      duration: 600 # seconds == 10 minutes
      os: windows-2022
      shell: cmd.exe
      targets: '["exec", "exec-file", "spawn"]'
