name: BusyBox
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-busybox.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/unix/busybox.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-busybox.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/unix/busybox.js
      - test/fuzz/**
    branches:
      - main
  schedule:
    - cron: "0 2 2 * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  fuzz:
    name: Fuzz
    uses: ./.github/workflows/reusable-fuzz.yml
    with:
      duration: 600 # seconds == 10 minutes
      os: ubuntu-24.04
      shell: /tmp/busybox/sh
      targets: '["exec", "exec-file", "spawn"]'
