name: PowerShell
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-powershell.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/win/powershell.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-powershell.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/win/powershell.js
      - test/fuzz/**
    branches:
      - main
  schedule:
    - cron: "20 2 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  fuzz:
    name: Fuzz
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@main
    with:
      iterations: 10000
      os: windows-2022
      shell: powershell.exe
      targets: '["exec", "exec-file", "spawn"]'
