name: No shell
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-no-shell.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/no-shell.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-no-shell.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/no-shell.js
      - test/fuzz/**
    branches:
      - main
  schedule:
    - cron: "0 2 5 * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  unix:
    name: Fuzz (Unix)
    uses: ./.github/workflows/reusable-fuzz.yml
    with:
      duration: 600 # seconds == 10 minutes
      os: ubuntu-24.04
      shell: "" # false
      targets: '["exec-file", "fork", "spawn"]'
  windows:
    name: Fuzz (Windows)
    uses: ./.github/workflows/reusable-fuzz.yml
    with:
      duration: 600 # seconds == 10 minutes
      os: windows-2025
      shell: "" # false
      targets: '["exec-file", "fork", "spawn"]'
