name: No shell
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-no-shell-win.yml
      - .github/workflows/reusable-fuzz.yml
      - src/win/no-shell.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-no-shell-win.yml
      - .github/workflows/reusable-fuzz.yml
      - src/win/no-shell.js
      - test/fuzz/**
    branches:
      - main
  schedule:
    - cron: "35 2 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  fuzz-windows:
    name: Fuzz Windows
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@main
    with:
      duration: 600 # seconds == 10 minutes
      os: windows-2022
      shell: "false"
      targets: '["exec-file", "fork", "spawn"]'
