name: Bash
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-bash.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/unix/bash.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-bash.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/unix/bash.js
      - test/fuzz/**
    branches:
      - main
  schedule:
    - cron: "0 2 1 * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  fuzz:
    name: Fuzz
    uses: ./.github/workflows/reusable-fuzz.yml
    with:
      duration: 600 # seconds == 10 minutes
      os: ubuntu-22.04
      shell: /bin/bash
      targets: '["exec", "exec-file", "spawn"]'
