name: PowerShell
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-powershell.yml
      - .github/workflows/reusable-fuzz.yml
      - src/win/powershell.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-powershell.yml
      - .github/workflows/reusable-fuzz.yml
      - src/win/powershell.js
      - test/fuzz/**
    branches:
      - main
  schedule:
    - cron: "20 2 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  specified-shell:
    name: Fuzz (specified)
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@ci-fuzz-system-shell
    with:
      duration: 600 # seconds == 10 minutes
      os: windows-2022
      shell: powershell.exe
      targets: '["exec", "exec-file", "spawn"]'
  system-shell:
    name: Fuzz (system)
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@ci-fuzz-system-shell
    with:
      duration: 600 # seconds == 10 minutes
      os: windows-2022
      shell: ""
      comspec: powershell.exe
      targets: '["exec", "exec-file", "fork", "spawn"]'
