name: No shell (Unix)
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-no-shell-unix.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/unix/no-shell.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-no-shell-unix.yml
      - .github/workflows/reusable-fuzz.yml
      - src/internal/unix/no-shell.js
      - test/fuzz/**
    branches:
      - main
  schedule:
    - cron: "0 2 5 * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  fuzz:
    name: Fuzz
    uses: ./.github/workflows/reusable-fuzz.yml
    with:
      duration: 600 # seconds == 10 minutes
      os: ubuntu-24.04
      shell: "" # false
      targets: '["exec-file", "fork", "spawn"]'
