name: CMD
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-cmd.yml
      - .github/workflows/reusable-fuzz.yml
      - src/win/cmd.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-cmd.yml
      - .github/workflows/reusable-fuzz.yml
      - src/win/cmd.js
      - test/fuzz/**
    branches:
      - main
  schedule:
    - cron: "5 2 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  fuzz:
    name: Fuzz
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@main
    with:
      duration: 600 # seconds == 10 minutes
      os: windows-2022
      shell: cmd
      targets: '["exec", "exec-file", "spawn"]'
