name: No shell
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-no-shell.yml
      - .github/workflows/reusable-fuzz.yml
      - src/unix/dash.js
      - src/win/cmd.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-no-shell.yml
      - .github/workflows/reusable-fuzz.yml
      - src/unix/dash.js
      - src/win/cmd.js
      - test/fuzz/**
    branches:
      - main
      - main-v1
  schedule:
    - cron: "25 2 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  fuzz-unix:
    name: Fuzz Unix
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@main-v1
    with:
      duration: 600 # seconds == 10 minutes
      os: ubuntu-22.04
      shell: "false"
      targets: '["exec", "exec-file", "fork", "spawn"]'
  fuzz-windows:
    name: Fuzz Windows
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@main-v1
    with:
      duration: 600 # seconds == 10 minutes
      os: windows-2022
      shell: "false"
      targets: '["exec", "exec-file", "fork", "spawn"]'
