name: Dash
on:
  pull_request:
    paths:
      - .github/workflows/fuzz-dash.yml
      - .github/workflows/reusable-fuzz.yml
      - src/unix/dash.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/fuzz-dash.yml
      - .github/workflows/reusable-fuzz.yml
      - src/unix/dash.js
      - test/fuzz/**
    branches:
      - main
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  fuzz:
    name: Fuzz
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@rework-ci-fuzz
    with:
      duration: 600 # seconds == 10 minutes
      os: ubuntu-22.04
      shell: /bin/dash
      targets: '["exec", "exec-file", "spawn"]'
