name: OSSF
on:
  pull_request: ~
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

permissions: read-all

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-22.04
    permissions:
      security-events: write # To upload SARIF results
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Perform OSSF Scorecard analysis
        uses: ossf/scorecard-action@80e868c13c90f172d68d1f4501dee99e2479f7af # v2.1.3
        with:
          publish_results: true
          results_file: ossf-scorecard-results.sarif
          results_format: sarif
      - name: Upload OSSF Scorecard report to GitHub
        uses: github/codeql-action/upload-sarif@d186a2a36cc67bfa1b860e6170d37fb9634742c7 # v2.2.11
        if: ${{ failure() || success() }}
        with:
          sarif_file: ossf-scorecard-results.sarif
