name: Rekor log monitor
on:
  push: ~
  schedule:
    - cron: "0 * * * *"

jobs:
  consistency_proof:
    name: Consistency proof
    permissions:
      contents: read
      issues: write # To file an issue on a monitoring failure
    uses: ericcornelissen/rekor-monitor/.github/workflows/reusable_monitoring.yml@fdd48b6846ddd3556192671cc2e9e220e72b8218
    with:
      artifact_retention_days: 14
      file_issue: true
  identity_check:
    name: Identity check
    needs:
      - consistency_proof
    permissions:
      contents: read
      issues: write # To file an issue on a monitoring failure
    uses: ericcornelissen/rekor-monitor/.github/workflows/reusable_monitoring.yml@fdd48b6846ddd3556192671cc2e9e220e72b8218
    with:
      artifact_retention_days: 14
      config: |
        monitoredValues:
          certIdentities:
          - certSubject: https://github\.com/ericcornelissen/shescape/blob/.+/\.github/workflows/.+\.yml@.+
            issuers:
            - https://token\.actions\.githubusercontent\.com
      file_issue: true
