name: Release
on:
  workflow_dispatch:
    inputs:
      update_type:
        description: Update type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions: read-all

jobs:
  initiate:
    name: Initiate
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Verify action checksums
        uses: ./.github/actions/ghasum
      - name: Install Node.js
        uses: actions/setup-node@v6.3.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Create automation token
        uses: actions/create-github-app-token@v3.1.1
        id: automation-token
        with:
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
      - name: Bump version
        env:
          UPDATE_TYPE: ${{ github.event.inputs.update_type }}
        run: npm version "$UPDATE_TYPE" --no-git-tag-version
      - name: Update src/index.js
        run: node script/release/bump-jsdoc.js
      - name: Update CHANGELOG
        run: node script/release/bump-changelog.js
      - name: Create Pull Request
        env:
          APP_TOKEN: ${{ steps.automation-token.outputs.token }}
          GH_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          UPDATE_TYPE: ${{ github.event.inputs.update_type }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout -B "release-${UPDATE_TYPE}"
          git add .
          git commit --message 'Version bump'

          git remote set-url origin "https://x-access-token:${APP_TOKEN}@github.com/${REPOSITORY}"
          git push --force origin "release-${UPDATE_TYPE}"

          gh pr create \
            --title="New ${UPDATE_TYPE} release" \
            --body='_This Pull Request was created automatically_

            ---

            ### Merge checklist

            - [ ] All continuous integration checks passed.
            - [ ] The version number is consistently updated in `package.json`, `package-lock.json`, and `src/index.js`.
            - [ ] A new release is added to `CHANGELOG.md` with the correct version number and date.
            - [ ] The new version number is in accordance with [Semantic Versioning].
            - [ ] There are no unexpected changes in the Pull Request.

            ### Post-merge checklist

            _It will take a few minutes for this to happen._

            - [ ] The new version is published to [npm].
            - [ ] A git tag for the new release is created.
            - [ ] A GitHub release is created.
            - [ ] The major version branch is updated.

            [npm]: https://www.npmjs.com/package/shescape
            [semantic versioning]: https://semver.org/spec/v2.0.0.html' \
            --base='main' --head="release-${UPDATE_TYPE}"
