name: Semgrep
on:
  pull_request: ~ # temp
  push:
    branches:
      - main

permissions: read-all

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # To upload SARIF results
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
      - name: Perform Semgrep analysis
        run: semgrep ci --sarif --output semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Upload Semgrep report to GitHub
        uses: github/codeql-action/upload-sarif@f6091c0113d1dcf9b98e269ee48e8a7e51b7bdd4 # v3.28.5
        if: ${{ failure() || success() }}
        with:
          sarif_file: semgrep.sarif
  malicious-code-ruleset:
    name: Malicious Code
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # To upload SARIF results
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
      - name: Get malicious-code-ruleset
        run: git clone https://github.com/apiiro/malicious-code-ruleset.git ../malicious-code-ruleset
      - name: Perform Semgrep analysis
        run: semgrep --config ../malicious-code-ruleset
