name: Weekly
on:
  schedule:
    - cron: "0 4 * * 6"
  workflow_dispatch: ~

permissions: read-all

jobs:
  npm-deps:
    name: Update transitive dependencies
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Verify action checksums
        uses: ./.github/actions/ghasum
      - name: Install Node.js
        uses: actions/setup-node@v6.3.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Create automation token
        uses: actions/create-github-app-token@v3.1.1
        id: automation-token
        with:
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
      - name: Install dependencies
        run: npm clean-install
      - name: Update dependencies
        run: |
          npm update --prefer-dedupe
      - name: Restore runtime dependency versions
        run: |
          npm install which@3.0.0
          sed -i 's/"which": "3.0.0"/"which": "^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0"/g' package*.json

          npm install @ericcornelissen/lregexp@1.0.7
          sed -i 's/"@ericcornelissen\/lregexp": "1.0.7"/"@ericcornelissen\/lregexp": "^1.0.7"/g' package*.json
      - name: Fix 'invalid typescript@5.6.1-rc' issue
        run: |
          npm install typescript@^5.0.0
          npm uninstall typescript
      - name: Create Pull Request
        env:
          APP_TOKEN: ${{ steps.automation-token.outputs.token }}
          GH_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout -B npm-transitive-dependencies
          git add package.json package-lock.json
          git commit --message 'Update transitive dependencies'

          git remote set-url origin "https://x-access-token:${APP_TOKEN}@github.com/${REPOSITORY}"
          git push --force origin npm-transitive-dependencies

          gh pr create \
            --title='Update transitive dependencies' \
            --body='_This Pull Request was created automatically_' \
            --base='main' --head='npm-transitive-dependencies' \
            --label='dependencies'
